// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Svjen1-XG8207IbudNl4Oq0Ue9I2mYw',
    appId: '1:1095271235921:web:2f17432447d5c69aaf9370',
    messagingSenderId: '1095271235921',
    projectId: 'sudoku-game-4c36a',
    authDomain: 'sudoku-game-4c36a.firebaseapp.com',
    storageBucket: 'sudoku-game-4c36a.firebasestorage.app',
    measurementId: 'G-J0PCTT2E2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaf9bk2byeLWBPORDDZxJgpZnv_pT3WL8',
    appId: '1:1095271235921:android:4746fc79ba259e26af9370',
    messagingSenderId: '1095271235921',
    projectId: 'sudoku-game-4c36a',
    storageBucket: 'sudoku-game-4c36a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6WymtIifwHTcmrX3zFwFKkICoyDIZjw',
    appId: '1:1095271235921:ios:8356113a47e51d61af9370',
    messagingSenderId: '1095271235921',
    projectId: 'sudoku-game-4c36a',
    storageBucket: 'sudoku-game-4c36a.firebasestorage.app',
    iosBundleId: 'com.prajwaldarekar.sudoku08',
  );
}
